### ISSUE TITLE
Problem about installation on Windows

### ISSUE THREAD

**Issue by YAEH-IO** [nagyrajmund/gesticulating_agent_unity#2]
Hi I have met some problem when transplanting the system on Windows. It shows that SoX might be missed but after I installed it with Anaconda Prompt manually it still shows like below:

```
'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

2021-03-11 17:33:39.571356: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-11 17:33:39.576738: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from gesture_generator_service import GestureGeneratorService
  File "D:\KTH_Courses_and_Practices\KTH_Master_Thesis\Implementation\gesticulating_agent_unity\gesticulator\gesticulator\interface\gesture_generator_service.py", line 11, in <module>
    from tts_interface import GlowTTS
  File "D:\KTH_Courses_and_Practices\KTH_Master_Thesis\Implementation\gesticulating_agent_unity\gesticulator\gesticulator\interface\tts_interface.py", line 61, in <module>
    TTS_CONFIG = load_config(TTS_CONFIG)
  File "d:\kth_courses_and_practices\kth_master_thesis\implementation\gesticulating_agent_unity\gesticulator\gesticulator\interface\tts_repo\TTS\utils\io.py", line 38, in load_config
    input_str = f.read()
  File "C:\Users\yuan-\Anaconda3\envs\gesturebot_blenderbot\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3230: character maps to <undefined>
(gesturebot_blenderbot) PS D:\KTH_Courses_and_Practices\KTH_Master_Thesis\Implementation\gesticulating_agent_unity\gesticulator\gesticulator\interface>
```
Have you met the same error before? Thank you very much.
Yuan

**Comment by nagyrajmund** [comment]
Hi Yuan,

The first error comes from a dependency of the TTS model. I would try installing sox from the binaries at [http://sox.sourceforge.net/](http://sox.sourceforge.net/) (instead of doing it in conda), and possibly also espeak ([http://espeak.sourceforge.net/download.html](http://espeak.sourceforge.net/download.html)).

The second error is also related to the TTS model - you can probably find an answer among the original repo's issues. [This one](https://github.com/mozilla/TTS/issues/648) seems relevant.

**Comment by nagyrajmund** [comment]
Closing the issue due to inactivity. Please feel free to reopen if you're still experiencing issues!
